/* metadata */
import type { Metadata } from "next";

/* styles */
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

/* fonts */
import { inter } from "@/lib/fonts/fonts";

/* components */
import { ToastContainer } from "react-toastify";
import HeaderLanding from "@/components/headers/HeaderLanding";
import Footer from "@/components/footer/FooterLanding";
import { unstable_ViewTransition as ViewTransition } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter} antialiased`}>
        <HeaderLanding />
        <ViewTransition name="Page">{children}</ViewTransition>
        <Footer />
        <ToastContainer position="top-right" autoClose={5000} />
      </body>
    </html>
  );
}
